FROM nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu22.04
WORKDIR /app
RUN apt-get update && apt-get install -y python3-pip python3-dev git && apt-get clean && rm -rf /var/lib/apt/lists/*
RUN pip3 install torch==2.4.1 torchvision==0.19.1 --index-url https://download.pytorch.org/whl/cu118
RUN pip3 install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu118/torch2.4.0/index.html
RUN git clone https://github.com/open-mmlab/mmediting.git /app/mmediting && cd /app/mmediting && pip3 install -r requirements.txt && pytho
RUN cd /app
RUN git clone https://github.com/caojiezhang/CiaoSR.git /app/CiaoSR
RUN cd /app/CiaoSR && pip3 install -r requirements.txt
RUN wget -P /pretrain_model https://github.com/caojiezhang/CiaoSR/releases/download/v1.0.0/edsr-ciaosr.pth 
RUN wget -P /pretrain_model https://github.com/caojiezhang/CiaoSR/releases/download/v1.0.0/rdn-ciaosr.pth 
RUN wget -P /pretrain_model https://github.com/caojiezhang/CiaoSR/releases/download/v1.0.0/swinir-ciaosr.pth 
WORKDIR /app/CiaoSR
CMD ["bash"]


